name: CI (core)

on:
  push:
    branches:
      - master
      - clean
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        rust:
          - nightly
          - stable

    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.rust }}
      - run: rustup default ${{ matrix.rust }}
      - run: cargo test

  fmt:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup default ${{ matrix.rust }}
      - run: rustup component add rustfmt
      - run: cargo fmt -- --check

  clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup default ${{ matrix.rust }}
      - run: rustup component add clippy
      - run: cargo clippy -- --deny warnings
